### ISSUE TITLE
CI fails

### ISSUE THREAD

**Issue by Sword-Smith** [Neptune-Crypto/neptune-core#205]
CI fails for these tests:

```
   models::state::global_state_tests::flaky_mutator_set_test
    models::state::global_state_tests::restore_wallet::offchain_generation_change_exists
    models::state::global_state_tests::restore_wallet::offchain_symmetric_change_exists
    models::state::global_state_tests::restore_wallet::onchain_generation_change_exists
    models::state::global_state_tests::restore_wallet::onchain_symmetric_change_exists
    models::state::mempool::tests::remove_transactions_with_block_test
    models::state::wallet::wallet_tests::wallet_state_maintanence_multiple_inputs_outputs_test
    rpc_server::rpc_server_tests::send_to_many_test
```

The code to estimate proving capabilities is defined in `networking_state.rs` as 
```rust
 pub(crate) fn estimate_proving_power() -> TxProvingCapability {
        const SINGLE_PROOF_CORE_REQ: usize = 19;
        const SINGLE_PROOF_MEMORY_USAGE: u64 = (1u64 << 30) * 128;
        const PROOF_COLLECTION_CORE_REQ: usize = 2;
        const PROOF_COLLECTION_MEMORY_USAGE: u64 = (1u64 << 30) * 16;

        let s = System::new_all();
        let total_memory = s.total_memory();
        assert!(
            !total_memory.is_zero(),
            "Total memory reported illegal value of 0"
        );

        let physical_core_count = s.physical_core_count().unwrap_or(1);

        if total_memory > SINGLE_PROOF_MEMORY_USAGE && physical_core_count > SINGLE_PROOF_CORE_REQ {
            TxProvingCapability::SingleProof
        } else if total_memory > PROOF_COLLECTION_MEMORY_USAGE
            && physical_core_count > PROOF_COLLECTION_CORE_REQ
        {
            TxProvingCapability::ProofCollection
        } else {
            TxProvingCapability::LockScript
        }
    }
```

The CI runs on a machine with *one* core which sets the `TxProvingCapability` to `LockScript`, which is not implemented in `create_transaction from_data_worker` in `GlobalState`:

```rust
        let proof = match proving_power {
            TxProvingCapability::LockScript => todo!(),
            TxProvingCapability::ProofCollection => {
                TransactionProof::ProofCollection(ProofCollection::produce(&primitive_witness))
            }
            TxProvingCapability::SingleProof => {
                TransactionProof::SingleProof(SingleProof::produce(&primitive_witness))
            }
        };
```

The solution is probably just to implement `LockScript` proving capabilities by adding a new `TransactionProof` enum of `Incomplete` that maybe only produces a proof for the lock script and relies on peers to create the other proofs.

**Comment by aszepieniec** [comment]
After a3fd2375782cd73cb9fca680c61296b8d733b8ff, the remaining failures are:
 -    `models::state::global_state_tests::restore_wallet::offchain_generation_change_exists`
 -    `models::state::global_state_tests::restore_wallet::offchain_symmetric_change_exists`
 -    `models::state::global_state_tests::restore_wallet::onchain_generation_change_exists`
 -    `models::state::global_state_tests::restore_wallet::onchain_symmetric_change_exists`
 -    `rpc_server::rpc_server_tests::send_to_many_test`.

I expect only the last failure remains after 9d491c63375abb28881b74c75b7d34e77f354f65.

This last test, `send_to_many_test` is tricky because it doesn't call `create_transaction` directly, and therefore there is no easy replacement with `create_transaction_with_prover_capability`.

An alternative to the solution you suggest might be (I'm not sure if it can work) to override the network configuration parameter in the test. Then the entire proving capability estimation would be bypassed.

**Comment by Sword-Smith** [comment]
These problems were solved by always setting the prover capability in all tests and then using the proof server to fetch proofs.
