### ISSUE TITLE
Write a list of snippets used for consensus

### ISSUE THREAD

**Issue by Sword-Smith** [Neptune-Crypto/neptune-core#252]
Compose a list of all Triton VM assembler snippets used in the consensus programs. This list is the basis of the internal security review we'll do on our Triton VM programs.

**Comment by jan-ferdinand** [comment]
### Identify all Consensus Programs

I have identified the following implementors of trait `ConsensusProgram`:

- `BlockProgram`
- `CoinbaseIsValid`
- `CollectLockScripts`
- `CollectTypeScripts`
- `CorrectControlParameterUpdate`
- `CorrectMmrUpdate`
- `CorrectMutatorSetUpdate`
- `KernelToOutputs`
- `Merge`
- `MmrMembership`
- `NativeCurrency`
- `PredecessorIsValid`
- `PrincipalBlockValidationLogic`
- `RemovalRecordsIntegrity`
- `SingleProof`
- `TimeLock`
- `Update`

I would appreciate some guidance:
- Does above list include all consensus-critical programs? In other words, are there consensus-critical programs that do not implement `ConsensusProgram`?
- Are any of the list's entries _not_ consensus-critical programs?

### Identify Imported Snippets

I have identified four possible pathways to identify all the Triton assembly snippets imported by consensus programs. All of them come with their pros & cons. My favorite is approach 3, “directly analyze `library`.” If you have additional approaches or additional pros or cons for existing approaches, I'd be happy to hear of them.

#### 1: Analyze the Program's Profile

- Pro: Requires no (or only little) change to existing APIs
- Con: Might not identify all imported assembly snippets due to conditional execution
- Con: Requires program execution, which in turn requires correct setup of the program's inputs

#### 2: Intercept Calls to `library.import`

- Pro: Identifies all imported assembly snippets
- Con: Technical feasibility / overhead is unclear to me

#### 3: Directly Analyze `library`

- Pro: Identifies all imported assembly snippets through `library.get_all_snippet_names()`
- Con: Requires introducing new API to return the `library` from a `ConsensusProgram`

#### 4: Iterate Over Entire Program to Fetch Labels

- Pro: Identifies all imported assembly snippets
- Con: Requires parsing labels to identify non-default labels
- Con: Probably lists snippet-internal labels, introducing noise

**Comment by Sword-Smith** [comment]
This approach looks solid to me. I think you identified all consensus programs, except maybe the two type scripts, `NativeCurrency` and `TimeLock`.
