### ISSUE TITLE
clippy warnings.

### ISSUE THREAD

**Issue by dan-da** [Neptune-Crypto/neptune-core#45]
While working on #44 I ran `cargo clippy` and noticed a lot of warnings.   Specifically:

```
$ cargo clippy 2>&1 | grep ^warning | wc -l
20
$ cargo clippy 2>&1 | grep ^warning
warning: useless use of `vec!`
warning: useless use of `vec!`
warning: useless use of `vec!`
warning: useless use of `vec!`
warning: useless use of `vec!`
warning: useless use of `vec!`
warning: useless use of `vec!`
warning: useless use of `vec!`
warning: useless use of `vec!`
warning: useless use of `vec!`
warning: useless use of `vec!`
warning: useless use of `vec!`
warning: useless use of `vec!`
warning: useless use of `vec!`
warning: useless use of `vec!`
warning: `neptune-core` (lib) generated 15 warnings (run `cargo clippy --fix --lib -p neptune-core` to apply 10 suggestions)
warning: usage of an `Arc` that is not `Send` or `Sync`
warning: usage of an `Arc` that is not `Send` or `Sync`
warning: usage of an `Arc` that is not `Send` or `Sync`
warning: `neptune-core` (bin "neptune-dashboard") generated 3 warnings
```

I can work on a PR to fix these.   Hopefully all are simple.

I was surprised to see the warnings as previously I've worked on projects where CI does not allow PRs to be accepted until all clippy warnings are resolved and also cargo fmt --check is clean.

Is that a policy we could consider implementing here?    Keeps things nice and tidy for everyone.

**Comment by Sword-Smith** [comment]
The `warning: useless use of `vec!`` usually means that we are concatenating vectors like this:
`vec![vec![a, b], vec![c]].concat()`. With `rustc` version 1.72.0 this became a clippy warning, as the outermost `Vec<T>` can be replaced by an array. So clippy wants you to write `[vec![a, b], c].concat()` instead.

This issue arose in several repos since the above, deprecated pattern was used a lot in our code.

I would have to do a little more digging into the `Arc`/`Send` issue. I don't know the solution to that from the top of my head.

**Comment by dan-da** [comment]
thx.   I'll take a look at cleaning these up tmw.   Maybe learn a bit more about the codebase in the process.

**Comment by Sword-Smith** [comment]
> thx. I'll take a look at cleaning these up tmw. Maybe learn a bit more about the codebase in the process.

To quickly get an overview of the code, you can start here:
https://github.com/Neptune-Crypto/neptune-core/blob/master/developer_docs/documentation_snapshots/20221011.md
